### ISSUE TITLE
Deactivate does not remove `tmpfiles.d` files created by system-manager

### ISSUE THREAD

**Issue by soupglasses** [numtide/system-manager#116]
When running `sudo system-manager deactivate` it will not remove tmpfiles as generated in `/etc/tmpfiles.d/00-system-manager.conf`.

For example, configuring `systemd.tmpfiles.rules = [ "D /var/tmp/system-manager 0755 root root -" ];` will not remove `/var/tmp/system-manager` during deactivation.

**Comment by r-vdp** [comment]
That's a limitation of systemd-tmpfiles, I don't think we can do much about that.
It's the same on nixos, if you switch to a generation that has a tmpfiles rule removed, there's no cleanup.

**Comment by soupglasses** [comment]
Yeah, I seem to have misunderstood the functionality of `tmpfiles`. As its not temporary, as the name hints to. Closing as its not technically a problem in system-manager.

**Comment by zimbatm** [comment]
This could be solved by translating the modules' tmpfiles to the system manager's state manager. If that works out nicely, the state manager could also be extracted and ported to NixOS. I believe we're (ab)using `systemd-tmpfiles` in NixOS because nothing better exists so far.

**Comment by aanderse** [comment]
we're not the only ones abusing it, though

i see it picking up traction in all sorts of places... and you can find a bunch of ports/rewrites of the spec used in places where `systemd` isn't

---

i assume `systemd` doesn't want to add this cleanup functionality... but has anyone actually asked?

**Comment by zimbatm** [comment]
@flokli might have asked.

If this gets extracted and made usable for NixOS, then other distros are also welcome to use it :)
