### ISSUE TITLE
Add option: environment.etc."file".recursive

### ISSUE THREAD

**Issue by Animeshz** [numtide/system-manager#18]
**Is your feature request related to a problem? Please describe.**

When creating a large folder symlink its useful to create symlink of individual files present in the source. As such if we want to for example use `environment.etc."".source = ./etc`, we won't be able to do it.

**Describe the solution you'd like**

Add `environment.etc."file".recursive = mkEnableOption "";`

**Describe alternatives you've considered**

\-

**Additional context**

\-

**Comment by aanderse** [comment]
I think this issue might be more appropriate for NixOS. `system-manager` is attempting to provide a NixOS compatible interface, not innovate NixOS modules. If such a feature lands in NixOS then it can trivially be ported here.

**Comment by Animeshz** [comment]
Thanks for the suggestion, closing this referencing a comment that already corresponds this request there: https://github.com/NixOS/nixpkgs/issues/200744#issuecomment-1566123737.
