### ISSUE TITLE
support for `environment.systemPackages`

### ISSUE THREAD

**Issue by aanderse** [numtide/system-manager#2]
**Is your feature request related to a problem? Please describe.**

It would be nice to have a single source to manage a system, including installed software.

**Describe the solution you'd like**

`environment.systemPackages` works well and obviously would improve compatibility with NixOS modules.

**Describe alternatives you've considered**

Managing software via `nix profile`.

**Additional context**

**Comment by R-VdP** [comment]
This is definitely something I want.

But I need to check a bit what would be the best way to get a directory of nix-provided binaries on the path of the host distro. We could probably fairly easily provision something similar to NixOS' `/run/current-system/sw/bin`.

**Comment by aanderse** [comment]
Debian based distros are pretty consistent following the `/etc/app.d/*.conf` pattern these days so there are some spots we could drop in a `./00-system-manager.conf` that might work well.

RHEL has a slightly different directory structure but still generally follows a similar pattern IIRC.

Looking forward to it.

**Comment by R-VdP** [comment]
Yeah I think we can probably do this by dropping a script in `/etc/profile.d` and have that set up a link in `/run` and add that to `PATH`. It's on my todo list.

**Comment by aanderse** [comment]
I did some experiments with this and it worked really well. For convenience I symlinked binaries to `/etc/system-manager/bin` because it was convenient with `environment.etc` but we could pick a better path without too much hassle.

**Comment by R-VdP** [comment]
Yeah, it's a bit heretic to have binaries in `/etc` though, even if they are symlinks.

What I'd do, is to add a script in `/etc/profile.d`, which will:
1. Check if `/run/system-manager/sw/bin` exists, and create it if not. This dir would be a symlink to the env that we generate using nix, containing the binaries to be added to `PATH` (`buildEnv` of all packages specified, including only their `bin` outputs).
1. Prepend this directory to `PATH`.

I need to find a couple of hours to implement this, hopefully one of the next weekends.

**Comment by aanderse** [comment]
That solution sounds *perfect*. Thanks!

**Comment by Animeshz** [comment]
Any updates?

**Comment by R-VdP** [comment]
@Animeshz could you try with #17 ?
