### ISSUE TITLE
A way to view and manage generations

### ISSUE THREAD

**Issue by nwn** [numtide/system-manager#34]
Aside from manually browsing through `/nix/var/nix/profiles/system-manager-profiles/`, is there a way to view prior generations of the system-manager profile? I tried using the `nix profile --profile <path>` command, but was unsuccessful. This would also be helpful when cleaning out older generations since running `nix-collect-garbage --delete-old` doesn't seem to detect system-manager profiles.

Something like the equivalent of `nix profile history` and `nix profile wipe-history` would be nice.

**Comment by R-VdP** [comment]
`nix-collect-garbage` should delete the profiles, if it doesn't then we need to check why that broke.

The profiles are normal nix profiles, so you can use the normal nix tools to manage them. For instance you can list them with `nix-env --list-generations --profile /nix/var/nix/profiles/system-manager-profiles/system-manager`

**Comment by nwn** [comment]
Sorry, you're right, these two commands do work to list the generations:

```
nix-env --list-generations --profile /nix/var/nix/profiles/system-manager-profiles/system-manager
   1   2023-07-17 04:21:23   
   2   2023-07-18 15:12:33   
   3   2023-07-19 12:44:49   
   4   2023-07-20 15:05:40   
   5   2023-07-21 14:33:15   
   6   2023-07-24 17:29:41   
   7   2023-07-28 11:49:31   (current)
```

```
nix profile history --profile /nix/var/nix/profiles/system-manager-profiles/system-manager
Version 1 (2023-07-17):
  No changes.

Version 2 (2023-07-18) <- 1:
  No changes.

Version 3 (2023-07-19) <- 2:
  No changes.

Version 4 (2023-07-20) <- 3:
  No changes.

Version 5 (2023-07-21) <- 4:
  No changes.

Version 6 (2023-07-24) <- 5:
  No changes.

Version 7 (2023-07-28) <- 6:
  No changes.
```

And similarly, using either of these commands will unlink old generations:
```
nix-env --delete-generations old --profile /nix/var/nix/profiles/system-manager-profiles/system-manager
```
```
nix profile wipe-history --profile /nix/var/nix/profiles/system-manager-profiles/system-manager
```

It's just `nix-collect-garbage --delete-old` which apparently doesn't work as it doesn't seem to find the system-manager profile. The above commands are sufficient though, so I'll close this issue. Thanks!
