### ISSUE TITLE
Support more systems

### ISSUE THREAD

**Issue by snylonue** [numtide/system-manager#78]
**Is your feature request related to a problem? Please describe.**

I'm trying to use system-manager on debian server, however it is not supported currently.

**Describe the solution you'd like**

Since ubuntu is supported and debian is similiar to it imo, maybe we can add support for it without much effort (maybe just relax the assertion)

**Describe alternatives you've considered**

**Additional context**

**Comment by mike-lloyd03** [comment]
Just ran into this on Arch. You can enable support on other distros with
```nix
system-manager.lib.makeSystemConfig.modules .config.system-manager.allowAnyDistro = true;
```

**Comment by r-vdp** [comment]
Did it work? Any issues?

**Comment by mike-lloyd03** [comment]
Yeah it works. No problems with system-manager itself. I got systemd services and /etc files working on Arch no problem. Trying to integrate it with home-manager right now but not having much luck.

**Comment by r-vdp** [comment]
Cool, closing this issue then.
