### ISSUE TITLE
Flake to combine it with home-manager

### ISSUE THREAD

**Issue by ShalokShalom** [numtide/system-manager#80]
**Is your feature request related to a problem? Please describe.**

Currently, its not really clear, how to combine home-manager with system-manager. 
I hope for some form of template, that showcases how to integrate the two.

**Describe the solution you'd like**

Standards are important. From my limited experience, it seems like combining system-manager with home-manager seems to be best done via a Flake. 

Considering both can describe packages (eg, have some overlap) I think its save to say, its sensible to find a standard solution, to combine the two projects. 

**Describe alternatives you've considered**

Running them side by side?

**Additional context**

I think its worth considering, to ship system-manager with home-manager integrated by default. 
People who are looking for one, probably also look for the other. Also, system-manager aims to provide the NixOS experience on non-NixOS. 

I think combining the two projects in an elegant way goes a long way towards that. 
Thank you very much ❤️

**Comment by mike-lloyd03** [comment]
I would love to see this especially for configuring my nix profile apps and theme.

**Comment by ShalokShalom** [comment]
I figured, that those two files are supposed to be separate. 

The Flake file can go whereever you want.

**Comment by mike-lloyd03** [comment]
Can you clarify what you mean? How did you integrate home-manager?

**Comment by ShalokShalom** [comment]
I didnt. Home-manager is not to be integrated with system manager. They are intended to run separately.
