### ISSUE TITLE
How to translate unit file to system-manager config?

### ISSUE THREAD

**Issue by jordan-bravo** [numtide/system-manager#88]
**Describe the bug**

This is not a bug but rather a question on usage.

My question is where to put the specific settings for a unit file.  For example, I am trying to re-create the systemd service that is created when Tailscale is installed with `apt`.

On Ubuntu 24.04, `sudo apt install tailscale` creates the following unit file:
`/etc/systemd/system/multi-user.target.wants/tailscaled.service`
```ini
[Unit]
Description=Tailscale node agent
Documentation=https://tailscale.com/kb/
Wants=network-pre.target
After=network-pre.target NetworkManager.service systemd-resolved.service

[Service]
EnvironmentFile=/etc/default/tailscaled
ExecStart=/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=${PORT} $FLAGS
ExecStopPost=/usr/sbin/tailscaled --cleanup

Restart=on-failure

RuntimeDirectory=tailscale
RuntimeDirectoryMode=0755
StateDirectory=tailscale
StateDirectoryMode=0700
CacheDirectory=tailscale
CacheDirectoryMode=0750
Type=notify

[Install]
WantedBy=multi-user.target
```

My System-Manager  `default.nix` file looks like this so far, but I'm not sure how to add the rest:
```nix
{ config, lib, pkgs, ... }:

{
  config = {
    nixpkgs.hostPlatform = "x86_64-linux";

    environment = {
      etc = {
       # What goes here?
      };
      systemPackages = [
        pkgs.hello
        pkgs.tailscale
      ];
    };

    systemd.services = {
      tailscaled = {
        enable = true;
        description = "Tailscale node agent";
        documentation = "https://tailscale.com/kb/";
        wants = [ "network-pre.target" ];
        after = [
          "network-pre.target"
          "NetworkManager.service"
          "systemd-resolved.service"
        ];
        serviceConfig = {
          Type = "notify";
        };
        wantedBy = [ "multi-user.target" ];
      };
    };
  };
}
```

Where would I add (and what is the syntax for) the following parts of the unit file?
- `EnvironmentFile=/etc/default/tailscaled`
- `ExecStart=/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=${PORT} $FLAGS`
- `ExecStopPost=/usr/sbin/tailscaled --cleanup`
- `Restart=on-failure`
- `RuntimeDirectory=tailscale`
- `RuntimeDirectoryMode=0755`
- `StateDirectory=tailscale`
- `StateDirectoryMode=0700`
- `CacheDirectory=tailscale`
- `CacheDirectoryMode=0750`

I tried looking through the source code of system-manager to get some hints but to be honest I'm struggling to find them.

**To Reproduce**

1. Attempt to create Tailscale unit file.
2. Get stumped.

**Expected behavior**

Would like some help or documentation on where each setting goes.

**System information**

Ubuntu 24.04

**Additional context**

I will also create an issue to suggest a discussion section for the repo so these kinds of questions don't clutter up the "Issues" section.

**Comment by aanderse** [comment]
all the items you listed go under `serviceConfig`

`system-manager` doesn't write code to do this really... just uses code from NixOS, some of which is copy+paste+modified... but for the most part fairly compatible with the original

https://search.nixos.org/options might provide some assistance for you
also consider looking at some NixOS modules

---

i had intended to reply to this when you originally posted the question but forgot about it... was reviewing some issues and found this - sorry

better late than never hopefully
